Timetables
[Wednesday](#wednesday)
[Thursday](#thursday)



#### Screen name
Zoom shows the name of each participant. It will be helpful if each person's name and centre are visible. When you sign in to the meeting, you can edit it easily - hover your mouse over your name in the “Participants” list , click on “Rename”, 

#### Privacy and data
The main presentations may be recorded. If so, you will see a notification on your screen. Recording part of the meeting enables us to review and access parts of our meeting in future.  
A list of participants is generated by registering for the meeting. To enable ease of communication, this list may be distributed. Please reply to this email if you would like your details to be withheld or wish to change your contact details.  

(#wednesday)
#### Timetable for Wednesday 13 May 2020
||Wednesday 13 May
--:|--
| 09:45 | Gather online                                                                                             
| 10:00 | Welcome and introduction                                                                                  
|       | Brief prayer to open                                                                                      
|       | Outline of day                                                                                           
|       | **Faith in Europe**: Archbishop Charles Scicluna                                    
| 10:45 | Small Groups                                                                                              
|       | In the small groups you will be with about 4 others with time to take a break, pray, reflect and discuss.
|       | Questions will be offered and each group will be helped by the timekeeper and notetaker it picks out.
| 11:30 | Plenary
       | When we come back together, we will hear from one another and address any comments or questions. 
| 12:30 | We will finish by 12:30 p.m.                                                                              

(#thursday)
#### Timetable for Thursday 14 May 2020
||Thursday 14 May 2020
--:|--
| 09:45 | Gather online                                                                                             
| 10:00 | Welcome and introduction                                                                                  
|       | Brief prayer to open                                                                                      
|       | Outline of day                                                                                           
|       | **Our mission in the light of the UAPs**: James Hanvey SJ                                    
| 10:45 | Small Groups                                                                                              
|       | In the small groups you will be with about 4 others with time to take a break, pray, reflect and discuss.
|       | Questions will be offered and each group will be helped by the timekeeper and notetaker it picks out.
| 11:30 | Plenary
       | When we come back together, we will hear from one another and address any comments or questions. 
|4:00| **Reflecting on the Ignatian Anniversaries**:
Franck Janin SJ
5:30|We will conclude by 5:30 p.m.  
